development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85
  socket: /opt/local/var/run/mysql5/mysqld.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85
  socket: /opt/local/var/run/mysql5/mysqld.sock