development:
  adapter: postgresql
  encoding: utf8
  database: myrailsapp_dev
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  database: myrailsapp_test
  pool: 5

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85

