development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85

