development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myrailsapp
  pool: 5
  username: heisenberg
  password: Cuculapraline85
<<<<<<< HEAD
  socket: /opt/local/var/run/mysql5/mysqld.sock
=======
>>>>>>> a79b2efa4d3db6a91738cdb857d3b03442b460ac
